<br>
<br>
<br>
<h1><center>Assignment 03</center></h1>
<h2><center>Exploratory Data Analysis</center></h2>
<h4><center>[ISYS2047] Information Systems Solutions and Design</center></h4>
<h3><center>Feature Selection</center></h3>
<br>
<div style="text-align: right"><h4>Student name: Juyeon Kim</h4></div>
<div style="text-align: right"><h4>Student ID: S3741327</h4></div>
<br></br>

## Import libraries

In [12]:
# Library for pickling
import joblib

# Also need pandas and nympy for some tasks
import pandas as pd
import numpy as np

# Library for splitting the data into train and test sets
from sklearn.model_selection import train_test_split 

# Libraries to select k best features
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

# 1. Load the cleaned data

In [13]:
# Load the pickled file
loan_df = joblib.load('loan-cleaned.pkl')  

# Check
loan_df.head()

customer_id   age  yrs_experience  family_size  education_level  income  \
0       3815.0  40.0             9.0          3.0              2.0    60.0   
1       5737.0  65.0            27.0          4.0              1.0    36.0   
2       4209.0  61.0             3.0          2.0              0.0   145.0   
3       4734.0  29.0            14.0          1.0              0.0    52.0   
4       2551.0  43.0            23.0          4.0              2.0    33.0   

   mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
0           0.0               1.0                0.0                 0.0   
1          90.0               0.0                0.0                 0.0   
2           0.0               0.0                0.0                 0.0   
3           0.0               0.0                0.0                 1.0   
4           0.0               0.0                0.0                 0.0   

   fixed_deposit_acct  online_acct  personal_loan  
0                 0.0          1.0              0  
1                 0.0          1.0              0  
2                 1.0          1.0              1  
3                 0.0          1.0              0  
4                 0.0          1.0              0

In [14]:
# Check
print(loan_df.shape)
print(loan_df.columns)

(6000, 13)
Index(['customer_id', 'age', 'yrs_experience', 'family_size',
       'education_level', 'income', 'mortgage_amt', 'credit_card_acct',
       'credit_card_spend', 'share_trading_acct', 'fixed_deposit_acct',
       'online_acct', 'personal_loan'],
      dtype='object')


# 2.  Split cleaned data into training & test sets

In [15]:
feature_cols = [ # all the features of loan_df
    'age', 
    'yrs_experience', 
    'family_size',
    'education_level', 
    'income', 
    'mortgage_amt', 
    'credit_card_acct',
    'credit_card_spend', 
    'share_trading_acct', 
    'fixed_deposit_acct',
    'online_acct'
]

X = loan_df[feature_cols]
#print('X:\n', X)

# Store the labels/target in variable y (lower case as its a single value)
y = loan_df['personal_loan']
#print('y:\n', y)

# Split into train/test set
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, # keep 20% for testing
                                                    random_state=2 # pass an int for reproducible rtesult
                                                    )

# 3.  Feature Selection

> ***Result*** <br>
> - 6 attempts were tried to find out the best feature selection.
> - Selected features will be reflected on files '05-assign3-model1-feature-selection' and '06-assign3-model2-feature-selection'. 

## Attempt 1. When k=10

> ***Result***
> - (1) online_acct was dropped as there's no value of online_acct in the rows of the numpy array. 

In [16]:
X_train.shape # 11 features in X_train

(4800, 11)

In [22]:
X_selected = SelectKBest(chi2, k=10).fit_transform(X_train, y_train) # k: reduce to 10 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 10)
[[ 63.   11.    1.    0.   19.    0.    0.    0.    0.    0. ]
 [ 35.   39.    4.    0.  144.    0.    0.    0.    0.    0. ]
 [ 34.   38.    2.    1.   55.    0.    1.    0.2   0.    0. ]
 [ 62.   12.    1.    0.   94.    0.    0.    0.    0.    0. ]
 [ 57.   32.    4.    2.   70.    0.    0.    0.    0.    0. ]
 [ 27.   31.    1.    0.   85.   95.    0.    0.    0.    0. ]
 [ 44.    3.    4.    1.   88.  237.    0.    0.    0.    1. ]
 [ 26.    7.    4.    1.   14.   98.    1.    1.    0.    0. ]
 [ 34.    7.    1.    0.  195.    0.    1.    0.    0.    0. ]
 [ 53.    8.    2.    1.   44.    0.    0.    0.    0.    1. ]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0

## Attempt 2. When k=9

> ***Result***
> - (1) credit_card_acct and (2) online_acct was dropped as there's no value of online_acct in the rows of the numpy array.

In [23]:
X_selected = SelectKBest(chi2, k=9).fit_transform(X_train, y_train) # k: reduce to 9 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 9)
[[ 63.   11.    1.    0.   19.    0.    0.    0.    0. ]
 [ 35.   39.    4.    0.  144.    0.    0.    0.    0. ]
 [ 34.   38.    2.    1.   55.    0.    0.2   0.    0. ]
 [ 62.   12.    1.    0.   94.    0.    0.    0.    0. ]
 [ 57.   32.    4.    2.   70.    0.    0.    0.    0. ]
 [ 27.   31.    1.    0.   85.   95.    0.    0.    0. ]
 [ 44.    3.    4.    1.   88.  237.    0.    0.    1. ]
 [ 26.    7.    4.    1.   14.   98.    1.    0.    0. ]
 [ 34.    7.    1.    0.  195.    0.    0.    0.    0. ]
 [ 53.    8.    2.    1.   44.    0.    0.    0.    1. ]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0

## Attempt 3. When k=8

> ***Result***
> - (1) age, (2) credit_card_acct, (3) online_acct was dropped as there's no value of online_acct in the rows of the numpy array.

In [26]:
X_selected = SelectKBest(chi2, k=8).fit_transform(X_train, y_train) # k: reduce to 8 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 8)
[[ 11.    1.    0.   19.    0.    0.    0.    0. ]
 [ 39.    4.    0.  144.    0.    0.    0.    0. ]
 [ 38.    2.    1.   55.    0.    0.2   0.    0. ]
 [ 12.    1.    0.   94.    0.    0.    0.    0. ]
 [ 32.    4.    2.   70.    0.    0.    0.    0. ]
 [ 31.    1.    0.   85.   95.    0.    0.    0. ]
 [  3.    4.    1.   88.  237.    0.    0.    1. ]
 [  7.    4.    1.   14.   98.    1.    0.    0. ]
 [  7.    1.    0.  195.    0.    0.    0.    0. ]
 [  8.    2.    1.   44.    0.    0.    0.    1. ]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0

## Attempt 4. When k=7

> ***Result***
> - (1) age, (2) credit_card_acct, (3) share_trading_acct, (4) online_acct was dropped as there's no value of online_acct in the rows of the numpy array.

In [28]:
X_selected = SelectKBest(chi2, k=7).fit_transform(X_train, y_train) # k: reduce to 7 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 7)
[[ 11.    1.    0.   19.    0.    0.    0. ]
 [ 39.    4.    0.  144.    0.    0.    0. ]
 [ 38.    2.    1.   55.    0.    0.2   0. ]
 [ 12.    1.    0.   94.    0.    0.    0. ]
 [ 32.    4.    2.   70.    0.    0.    0. ]
 [ 31.    1.    0.   85.   95.    0.    0. ]
 [  3.    4.    1.   88.  237.    0.    1. ]
 [  7.    4.    1.   14.   98.    1.    0. ]
 [  7.    1.    0.  195.    0.    0.    0. ]
 [  8.    2.    1.   44.    0.    0.    1. ]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0

## Attempt 5. When k=6

> ***Result***
> - (1) age, (2) family_size, (3) credit_card_acct, (4) share_trading_acct, (5) online_acct was dropped as there's no value of online_acct in the rows of the numpy array.

In [30]:
X_selected = SelectKBest(chi2, k=6).fit_transform(X_train, y_train) # k: reduce to 6 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 6)
[[ 11.    0.   19.    0.    0.    0. ]
 [ 39.    0.  144.    0.    0.    0. ]
 [ 38.    1.   55.    0.    0.2   0. ]
 [ 12.    0.   94.    0.    0.    0. ]
 [ 32.    2.   70.    0.    0.    0. ]
 [ 31.    0.   85.   95.    0.    0. ]
 [  3.    1.   88.  237.    0.    1. ]
 [  7.    1.   14.   98.    1.    0. ]
 [  7.    0.  195.    0.    0.    0. ]
 [  8.    1.   44.    0.    0.    1. ]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0

## Attempt 6. When k=5

> ***Result***
> - (1) age, (2) family_size, (3) credit_card_acct, (4) share_trading_acct, (5) online_acct, (6)credit_card_spend was dropped as there's no value of online_acct in the rows of the numpy array.

In [32]:
X_selected = SelectKBest(chi2, k=5).fit_transform(X_train, y_train) # k: reduce to 5 features in total. 

# Print the type and shape of the selected features
print(type(X_selected))
print(X_selected.shape)

# Print the first 10 rows of the selected features
np.set_printoptions(suppress=True) # Suppress scientific notation when printing
print(X_selected[:10])

# Print the first 10 rows of all the features in the dataset
X_train.head(10)

<class 'numpy.ndarray'>
(4800, 5)
[[ 11.   0.  19.   0.   0.]
 [ 39.   0. 144.   0.   0.]
 [ 38.   1.  55.   0.   0.]
 [ 12.   0.  94.   0.   0.]
 [ 32.   2.  70.   0.   0.]
 [ 31.   0.  85.  95.   0.]
 [  3.   1.  88. 237.   1.]
 [  7.   1.  14.  98.   0.]
 [  7.   0. 195.   0.   0.]
 [  8.   1.  44.   0.   1.]]


age  yrs_experience  family_size  education_level  income  \
2973  63.0            11.0          1.0              0.0    19.0   
2774  35.0            39.0          4.0              0.0   144.0   
3281  34.0            38.0          2.0              1.0    55.0   
2512  62.0            12.0          1.0              0.0    94.0   
457   57.0            32.0          4.0              2.0    70.0   
5505  27.0            31.0          1.0              0.0    85.0   
2002  44.0             3.0          4.0              1.0    88.0   
3306  26.0             7.0          4.0              1.0    14.0   
3685  34.0             7.0          1.0              0.0   195.0   
1071  53.0             8.0          2.0              1.0    44.0   

      mortgage_amt  credit_card_acct  credit_card_spend  share_trading_acct  \
2973           0.0               0.0                0.0                 0.0   
2774           0.0               0.0                0.0                 0.0   
3281           0.0               1.0                0.2                 0.0   
2512           0.0               0.0                0.0                 0.0   
457            0.0               0.0                0.0                 0.0   
5505          95.0               0.0                0.0                 0.0   
2002         237.0               0.0                0.0                 0.0   
3306          98.0               1.0                1.0                 0.0   
3685           0.0               1.0                0.0                 0.0   
1071           0.0               0.0                0.0                 0.0   

      fixed_deposit_acct  online_acct  
2973                 0.0          0.0  
2774                 0.0          1.0  
3281                 0.0          1.0  
2512                 0.0          1.0  
457                  0.0          1.0  
5505                 0.0          0.0  
2002                 1.0          0.0  
3306                 0.0          1.0  
3685                 0.0          1.0  
1071                 1.0          1.0